version: "3"

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "~/data/database"

  wordpress_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "~/data/www"

services:
  mariadbb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    env_file: .env
    ports:
      - 3306:3306
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    restart: unless-stopped
  
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    env_file: .env
    depends_on:
      - mariadb
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    restart: unless-stopped

  networks:
    inception:
      driver: bridge